version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/var/www/html"
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
      MONGO_INITDB_DATABASE: "ca"
      MONGODB_USER: "ca"
      MONGODB_DATABASE: "ca"
      MONGODB_PASS: "123456"
    ports:
      - "27017:27017"
    volumes:
      - ./src/db/seed/:/docker-entrypoint-initdb.d/init.js:ro